# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Snake_water_gun_game.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 400)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 255, 255);")
        self.l1 = QtWidgets.QLineEdit(Form)
        self.l1.setGeometry(QtCore.QRect(350, 70, 87, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setStyleSheet("background-color: rgb(67, 235, 235);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);")
        self.l1.setText("")
        self.l1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QLineEdit(Form)
        self.l2.setGeometry(QtCore.QRect(20, 250, 184, 29))
        font = QtGui.QFont()
        font.setFamily("Vineta BT")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.l2.setFont(font)
        self.l2.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"color: rgb(0, 0, 0);")
        self.l2.setAlignment(QtCore.Qt.AlignCenter)
        self.l2.setText("")
        self.l2.setObjectName("l2")
        self.l3 = QtWidgets.QLineEdit(Form)
        self.l3.setGeometry(QtCore.QRect(270, 250, 185, 29))
        font = QtGui.QFont()
        font.setFamily("Vineta BT")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.l3.setFont(font)
        self.l3.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.l3.setAlignment(QtCore.Qt.AlignCenter)
        self.l3.setText("")
        self.l3.setObjectName("l3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(170, 320, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Vineta BT")
        font.setPointSize(9)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 202, 202);")
        self.pushButton.clicked.connect(self.checkResult)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 70, 282, 23))
        font = QtGui.QFont()
        font.setFamily("Vineta BT")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(250, 210, 231, 23))
        font = QtGui.QFont()
        font.setFamily("Vineta BT")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 210, 171, 23))
        font = QtGui.QFont()
        font.setFamily("Vineta BT")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.result_L = QtWidgets.QLabel(Form)
        self.result_L.setGeometry(QtCore.QRect(50, 120, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Vineta BT")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.result_L.setFont(font)
        self.result_L.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result_L.setStyleSheet("color: rgb(114, 17, 127);")
        self.result_L.setAlignment(QtCore.Qt.AlignCenter)
        self.result_L.setObjectName("result_L")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Vineta BT")
        font.setPointSize(10)
        font.setUnderline(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 40, 451, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Snake water Gun game"))
        self.pushButton.setText(_translate("Form", "Start"))
        self.label.setText(_translate("Form", "Enter either s,w or g:"))
        self.label_3.setText(_translate("Form", "Computer Choice"))
        self.label_2.setText(_translate("Form", "Your Choice"))
        self.result_L.setText(_translate("Form", "Result!"))
        self.label_4.setText(_translate("Form", "---: s - Snake : w - Water : g - Gun :---"))

    def swg(self,comp,mine):
        if (comp == mine):
                return None
        elif (comp == 's' and mine == 'g'):
                return True
        elif (comp == 'w' and mine == 's'):
                return True
        elif (comp == 'g' and mine == 'w'):
                return True
        else:
                return False

    def checkResult(self):
        if self.l1.text() =='s' or self.l1.text() =='w' or self.l1.text() =='g':
                mine = self.l1.text()
                choose = ['s','w','g']
                comp = random.randint(0,2)
                comp = choose[comp]
                self.l2.setText(mine)
                self.l3.setText(comp)
                win = self.swg(comp,mine)
                if win:
                        self.result_L.setText("IRON MAN WIN")
                elif win is None:
                        self.result_L.setText("MATCH DRAW")
                else:
                        self.result_L.setText("IRON MAN LOSS")

        else:
                msg ="Please enter valid later."
                self.shwdlg(msg)
        self.l1.setText('')

    def shwdlg(self,msg):
        Dlg=QtWidgets.QMessageBox()
        Dlg.setText(msg)
        Dlg.setWindowTitle("Fantacy Cricket Game")
        self.l2.setText('')
        self.l3.setText('')
        ret=Dlg.exec()


if __name__ == "__main__":
    import sys
    import random
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
